site_name: Curumim
repo_url: https://github.com/UnBArqDsw2021-1/2021.1_G6_Curumim

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt

nav:
        - Home: index.md
        - Contribuição: 
                - Guia de Contribuição: guia-contrib.md
                - Políticas de Contribuição: politicas.md
        - Base:
                - Design Sprint:
                        - Documento de Design Sprint: base/design-sprint/doc-design-sprint.md
                        - Prototipação:
                                - Introdução: base/design-sprint/prototipos.md
                                - Protótipo de baixa fidelidade: base/design-sprint/prototipo-baixa.md
                                - Plano de testes de alta fidelidade: base/design-sprint/plan-test.md
                                - Protótipo de alta fidelidade: base/design-sprint/prototipo-alta.md
                - Requisitos:
                        - Pré-rastreabilidade:
                                - 5W2H: base/requisitos/pre-rastreabilidade/5w2h.md
                                - Argumentação: base/requisitos/pre-rastreabilidade/argumentacao.md
                                - Mapa Mental: base/requisitos/pre-rastreabilidade/mapa-mental.md
                                - Rich Picture: base/requisitos/pre-rastreabilidade/rich-picture.md
                        - Elicitação:
                                - Brainstorming: base/requisitos/elicitacao/brainstorming.md
                                - Personas: base/requisitos/elicitacao/personas.md
                                - StoryBoards: base/requisitos/elicitacao/storyboards.md
                                - Introspecção: base/requisitos/elicitacao/introspeccao.md
                        - Priorização:
                                - MoSCoW: base/requisitos/priorizacao/moscow.md
                                - First Things First: base/requisitos/priorizacao/first-things-first.md
                        - Modelagem:
                                - Especificação Suplementar: base/requisitos/modelagem/especificacao-suplementar.md
                                - Léxicos: base/requisitos/modelagem/lexicos.md
                                - NFR Framework: base/requisitos/modelagem/nfr-framework.md
                                - iStar: base/requisitos/modelagem/i-star.md
                - Metodologia:
                        - Metodologia: base/metodologia/metodologia.md
                        - Modelagem BPMN: base/metodologia/bpmn.md
                - Causa e efeito: causa-efeito.md
                - Product Backlog: product-backlog.md
                - TAP: base/tap/tap.md
        - Modelagem:
                - Modelagem Estática:
                        - Diagrama de pacotes: modelagem/modelagem-estatica/diagrama-de-pacotes.md
                - Modelagem Dinâmica:
                        - Casos de uso: modelagem/modelagem-dinamica/casos-de-uso.md
        - Reuniões:
                - ATA reunião 26/07: reunioes/r1-ata-26-07.md
                - ATA reunião 28/07: reunioes/r2-ata-28-07.md
                - Sprints:
                        - Sprint 0:
                                - Planning: reunioes/sprints/planning-sprint0.md
                                - Review: reunioes/sprints/review-sprint0.md
                        - Sprint 1:
                                - Planning: reunioes/sprints/planning-sprint1.md
                                - Review: reunioes/sprints/review-sprint1.md