site_name: My docs

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt

nav:
        - Home: index.md
        - Base:
                - Design Sprint:
                        - Documento de Design Sprint: base/design-sprint/doc-design-sprint.md
                        - Protótipos: base/design-sprint/prototipos.md
                - Requisitos:
                        - Elicitação:
                                - Brainstorming: base/requisitos/elicitacao/brainstorming.md
                                - Personas: base/requisitos/elicitacao/personas.md
                                - Story Boards: base/requisitos/elicitacao/story-boards.md
                                - Introspecção: base/requisitos/elicitacao/introspeccao.md
                        - Priorização:
                                - MoSCoW: base/requisitos/priorizacao/moscow.md
                                - First Things First: base/requisitos/priorizacao/first-things-first.md
                        - Pré-rastreabilidade:
                                - 5W2H: base/requisitos/pre-rastreabilidade/5w2h.md
                                - Mapa Metal: base/requisitos/pre-rastreabilidade/mapa-mental.md
                                - Rich Picture: base/requisitos/pre-rastreabilidade/rich-picture.md
                                - Argumentação: base/requisitos/pre-rastreabilidade/argumentacao.md
                - Metodologia:
                        - Metodologia: base/metodologia/metodologia.md
        - Reuniões:
                - ATA reunião 26/07: reunioes/r1-ata-26-07.md
                - ATA reunião 28/07: reunioes/r1-ata-28-07.md
